[package]
name = "search_t"
version = "0.1.0"
authors = ["Volodymyr Yevtushenko <voloyev@vivaldi.net>"]
edition = "2018"

[dependencies]
tempdir = "*"
tantivy = "0.7.2"

actix = "0.7"
actix-web = "0.7"

serde = "1.0"
serde_derive = "1.0"

log = "0.4.0"
env_logger = "0.6.0"